[package]
name = "RustRedirect"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
serde = "1.0.139"
serde_json = "1.0.82"
reql = "0.11.0"
dotenv = "0.15.0"